---
baseURL: https://tir-volson.ch
languageCode: fr-fr
title: Société de Tir du Volson
theme: piko
paginate: "9"
copyright: Société de Tir du Volson
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  hideFooter: true
  ShareButtons: [] # ["twitter","telegram","whatsapp"]
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  description: Site de la Société de Tir du Volson, pour rester au courant du programme de tir annuel, ainsi que de nos événements.
  math: false
  TitleImage: /uploads/title.jpg
    #images:
    #- "/uploads/title.jpg"
  label:
    title:  _Société de Tir du Volson_
    text: Bienvenue
    lightNavIcon: /uploads/favicon.png
    darkNavIcon: /uploads/favicon.png
    iconHeight: "35"
    iconWIdth: "35"
  comments: false
  mainSections:
  - blog
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  ShowRelated: true
  disableAnchoredHeadings: false
    #CookieNotice: Nous utilisons des cookies pour améliorer votre expérience sur notre site.
    #CookieLink: /legal/privacy/#cookies-and-web-beacons
    #CookieButton: Cookies Policy
  contactFormAction: #https://formsubmit.io/send/test@wouaib.ch
  assets:
    disableFingerprinting: true
    favicon: /uploads/favicon.png
    favicon16x16: /uploads/favicon.png
    favicon32x32: /uploads/favicon.png
    apple_touch_icon: /uploads/favicon.png
    safari_pinned_tab: /uploads/favicon.png
  ShowReadingTime: false
  ShowBreadCrumbs: false
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Société de Tir du Volson
    heroDescription: Votre société de tir de l'est lausannois
    heroCTAPrimaryText: News
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contactez-nous
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/title.jpg"
    # Blog Section
    disableBlogSection: false
    blogTitle: Actualités
    blogDescription: Nos dernières actualités
    seeMoreText: Plus d'articles
    # About Section    
    disableAboutSection: false
    aboutTitle: Info
    aboutDescription: en bref
    aboutImgUrl: "/uploads/pas.jpg"
    aboutContent: |
      La société de tir du Volson est active à Pully, au stand de Volson, dans le domaine du tir au <b>pistolet à 25 mètres</b>. Une section 300 mètres est également ouverte au stand de Vernand (à Romanel-sur-Lausanne) pour le tir au fusil.
      <br />
      <br />
      Elle fait partie des sociétés sportives de Pully et est membre de la Promotion Pully Paudex Belmont (PPPB), ainsi que de l’union des sociétés de tir de la région lausannoise (USTL).
      <br />
      <br />
      Nous organisons des entraînements, des concours internes, des tirs militaires (PO programme obligatoire) et participons à des concours de tir externes et au tir militaire en campagne.
    # Portfolio Section
    disablePortfolioSection: true
    portfolioTitle: En images
    portfolioDescription: Voici quelques images du stand et de nos activités.
    portfolio:
    - imageUrl: /uploads/portfolio-1.webp
      alt: # image alt for better SEO
      description: Tir du Grütli.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Tir du Röstigraben.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Barbecue journée portes ouvertes.
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Actualité
    title: Actualité
    pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Historique
    title: Historique
    pre: archive
    url: "/historique"
    weight: "30"
  - name: Infos
    title: Infos pratiques
    pre: map-pin
    url: "/infos"
    weight: "35"
  - name: Recherche
    pre: search
    url: "/chercher"
    weight: "40"
  - name: Contact
    pre: mail
    url: "/contact"
    weight: "50"
  search: # Search page's quick links
  - name: Catégories
    url: "/categories"
    weight: "10"
      #  - name: Archives
      #title: Archives
      #url: "/archives"
      #weight: "20"
  - name: Tags
    url: "/tags"
    weight: "30"
